spring:
    profiles:
        active: local
    datasource:
        url: jdbc:mysql://localhost:3306/ddukbbegi?useSSL=false&serverTimezone=UTC
        username: root
        password: ghks9430
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create # 또는 create, create-drop, validate 중 선택
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    data:
        redis:
            host: localhost
            port: 6379

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 94016094456-seu9l8kmf97ihftb7o80m4rhl4tkajhj.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                            - profile
                            - email
                        redirect-uri: "http://localhost:8080/login/oauth2/code/google"
                        authorization-grant-type: authorization_code
                        client-name: Google
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: sub
jwt:
  secret:
    key: BvdCDROpy/QRNPizw10GXalXzl41f/YOK2SfJNK2s+w=